survey_id : 'SimpleHubble'
field_id : '10nJy'
sed_model : 'beta'
morph_model : 'cSersic'
phot_model : 'idealisedimagePSF'
pz_model : 'eazy'
detection_filters : ['Hubble.WFC3.f105w', 'Hubble.WFC3.f125w', 'Hubble.WFC3.f160w']
